print("========== RECEIPT ==========")
print("Item\t\tPrice")
print("-----------------------------")
print("Notebook\t₹50")
print("Pen\t\t₹20")
print("Bag\t\t₹500")
print("-----------------------------")
print("Total\t\t₹570")
print("=============================")